services:
  supernode:
    image: flwr/supernode:${FLWR_VERSION:-1.18.0}
    command:
      - --superlink
      - ${SUPERLINK_IP:-100.78.235.15}:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=2"
      - --root-certificates
      - certificates/superlink-ca.crt
    secrets:
      - source: superlink-ca-certfile
        target: /app/certificates/superlink-ca.crt

  clientapp:
    build:
      context: ${PROJECT_DIR:-..}
      dockerfile_inline: |
        FROM flwr/clientapp:${FLWR_VERSION:-1.18.0}

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flwr-clientapp"]
    command:
      - --insecure
      - --clientappio-api-address
      - supernode:9094
    volumes:
      - "${PWD}/client/data:/app/data"
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode

secrets:
  superlink-ca-certfile:
    file: ../superlink-certificates/ca.crt
