[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl_server"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr",
    "torch==2.5.1",
    "scikit-learn",
    "numpy",
    "docker",
    "matplotlib",
    "pandas",
    "streamlit",
    "prometheus_client"
]

[tool.hatch.build.targets.wheel]
packages = ["."]
