# Jika server dijalankan secara lokal,
# maka isikan `ip` dengan "127.0.0.1" atau "localhost".
# Dalam kasus ini, Anda **wajib** menambahkan `ip_pub`, yaitu IP publik
# yang bisa diakses oleh seluruh host (klien) selama proses deployment.

server:
  # ip: 192.168.1.0
  # username: server1
  ip: localhost
  ip_pub: 100.92.52.29
  username: ubuntu

clients:
  # - ip: 192.168.1.1
  #   ip_pub: 192.168.1.1
  #   username: client1
  # - ip: 192.168.1.2
  #   ip_pub: 192.168.1.2
  #   username: client2
  - ip: 100.94.161.72
    username: ubuntu
  - ip: 100.118.164.99
    username: ubuntu
  - ip: 100.74.159.17
    username: ubuntu
