# Jika server dijalankan secara lokal,
# maka isikan `ip` dengan "127.0.0.1" atau "localhost".
# Dalam kasus ini, Anda **wajib** menambahkan `ip_pub`, yaitu IP publik
# yang bisa diakses oleh seluruh host (klien) selama proses deployment.

server:
  # ip: localhost
  # ip_pub: 192.168.1.0
  # username: server1
  ip: localhost
  ip_pub: 127.0.0.1
  username: runner

clients:
  # - ip: 192.168.1.1
  #   username: client1
  # - ip: 192.168.1.2
  #   username: client2
  - ip: localhost
    ip_pub: 127.0.0.1
    username: runner
  - ip: localhost
    ip_pub: 127.0.0.1
    username: runner
