# Jika server dijalankan secara lokal,
# maka isikan `ip` dengan "127.0.0.1" atau "localhost".
# Dalam kasus ini, Anda **wajib** menambahkan `ip_pub`, yaitu IP publik
# yang bisa diakses oleh seluruh host (klien) selama proses deployment.

server:
  # ip: localhost
  # ip_pub: 100.120.105.71
  # username: foxcat
  ip: 100.78.235.15
  username: capstoneadmin

clients:
  # - ip: localhost
  #   ip_pub: 100.74.159.17
  #   username: ubuntu
  - ip: 100.74.159.17
    username: ubuntu
  - ip: 100.118.164.99
    username: ubuntu
  - ip: 100.94.161.72
    username: ubuntu
