# Jika server dijalankan secara lokal,
# maka isikan `ip` dengan "127.0.0.1" atau "localhost".
# Dalam kasus ini, Anda **wajib** menambahkan `ip_pub`, yaitu IP publik
# yang bisa diakses oleh seluruh host (klien) selama proses deployment.

server:
  # ip: 100.78.235.15
  # username: capstoneadmin
  ip: localhost
  ip_pub: 127.0.0.1
  username: runner

clients:
  # - ip: localhost
  #   ip_pub: 100.74.159.17
  #   username: ubuntu
  - ip: localhost
    ip_pub: 127.0.0.1
    username: runner
  - ip: localhost
    ip_pub: 127.0.0.1
    username: runner
  - ip: localhost
    ip_pub: 127.0.0.1
    username: runner
