FROM flwr/serverapp:1.18.0

WORKDIR /app

COPY --chown=app:app pyproject.base.toml pyproject.toml
RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
    && python -m pip install -U --no-cache-dir .

ENTRYPOINT ["flwr-serverapp"]