apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp
  namespace: flwr
  labels:
    app: serverapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverapp
  template:
    metadata:
      labels:
        app: serverapp
    spec:
      imagePullSecrets:
        - name: regcre
      containers:
        - name: serverapp
          image: 100.78.235.15:8887/ronaa9488/federatedlearningdiabetesdetection/serverapp:latest
          args:
            - --insecure
            - --serverappio-api-address
            - superlink:9091
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: serverapp
  namespace: flwr
spec:
  type: ClusterIP
  selector:
    app: serverapp
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
