apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernode
  namespace: flwr
  labels:
    app: supernode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supernode
  template:
    metadata:
      labels:
        app: supernode
    spec:
      containers:
        - name: supernode
          image: flowerai/public/supernode:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: supernode
  namespace: flwr
spec:
  type: ClusterIP
  selector:
    app: supernode
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
