- hosts: clients
  serial: 1
  gather_facts: false
  tasks:
    - name: Restart semua container Docker
      become: true
      shell: |
        docker compose -f ./client/compose.yml down --volumes --remove-orphans
        docker image prune -f
        docker compose -f ./client/compose.yml up -d --build
      args:
        chdir: "/home/{{ ansible_user }}/fl_{{ inventory_hostname }}"

- hosts: server
  gather_facts: false
  tasks:
    - name: Restart server container
      become: true
      shell: |
        docker compose -f ./server/compose.yml down --volumes --remove-orphans
        docker image prune -f
        docker compose -f ./server/compose.yml up -d --build
      args:
        chdir: "/home/{{ ansible_user }}/fl_{{ inventory_hostname }}"
