name: Build & Push Client Images to GHCR

on:
  push:
    branches: [Aqil]
    # paths:
    #   - "distributed/client/**"
    #   - "distributed/server/**"
    #   - ".github/workflows/docker-build.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}

jobs:
  build-and-push:
    name: 🔨 Build and Push Images
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push serverapp image
        run: |
          docker build -f distributed/server/Dockerfile.serverapp -t $REGISTRY/$IMAGE_NAMESPACE/serverapp:latest server
          docker push $REGISTRY/$IMAGE_NAMESPACE/serverapp:latest

      - name: Build and Push clientapp image
        run: |
          docker build -f distributed/client/Dockerfile.clientapp -t $REGISTRY/$IMAGE_NAMESPACE/clientapp:latest client
          docker push $REGISTRY/$IMAGE_NAMESPACE/clientapp:latest

      - name: Build and Push streamlit image
        run: |
          docker build -f distributed/client/Dockerfile.streamlit -t $REGISTRY/$IMAGE_NAMESPACE/streamlit:latest client
          docker push $REGISTRY/$IMAGE_NAMESPACE/streamlit:latest
